### PR TITLE
Docs, CI, copyright update

### PR DESCRIPTION
**Pull request by tkchafin**
- Add minimap2 case to CI
- Note interleaved fastq input expected 
- Update copyright 

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/sanger-tol/readmapping/tree/master/.github/CONTRIBUTING.md)
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by tkchafin** [comment]
TODO -- Something with the cram_filter image or how we are passing it
```
Command executed:

  generate_cram_csv.sh 31231_3%231.subset.cram mMelMel1_T1_cram.csv 31231_3%231.subset.cram.crai 10000
  
  cat <<-END_VERSIONS > versions.yml
  "SANGERTOL_READMAPPING:READMAPPING:ALIGN_ILLUMINA:GENERATE_CRAM_CSV":
      samtools: $(echo $(samtools --version 2>&1) | sed 's/^.*samtools //; s/Using.*$//' )
  END_VERSIONS

Command exit status:
  255

Command output:
  (empty)

Command error:
  FATAL:   could not open image /home/runner/work/readmapping/readmapping/quay.io-sanger-tol-cramfilter_bwamem2_minimap2_samtools_perl-0.001-c1.img: image format not recognized
```

**Comment by muffato** [comment]
@gq1 . Is it similar to the issue we've seen on the treeval and genomeassembly pipelines where we had to switch to singularity / pre-download the container ?

**Comment by gq1** [comment]
> @gq1 . Is it similar to the issue we've seen on the treeval and genomeassembly pipelines where we had to switch to singularity / pre-download the container ?

I think it is different. We ran out of disk space there when pulling docker image, or later pulling docker image into singularity image.

In this workflow, it already uses singularity and nf-core download.
Can we define NXF_SINGULARITY_CACHEDIR in work flow level like this? https://github.com/sanger-tol/treeval/blob/b7475b78747ff90101e8418fd82332f1abb163fa/.github/workflows/ci.yml#L11 

Why we need this workflow when we already the CI one? Any more to test?

**Comment by tkchafin** [comment]
Removed the `download_pipeline.yml` as this was only introduced due to nf-core template change, and had redundant functionality with `ci.yml` which already tested pipeline can be run and images downloaded. This should be ready to review now

**Pull request closed without merging**
