### PR TITLE
merge bwamem_index and remove unneeded multiqc options

### PR DESCRIPTION
**Pull request by tkchafin**
## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/sanger-tol/readmapping/tree/master/.github/CONTRIBUTING.md)
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by tkchafin** [comment]
@reichan1998 Good catch on the `-resume` issue! I think I have figured it out and fixed the issue. The problem was caused by special characters in the file names for the hic and illumina samples, and the fact that I was saving meta.file as a file object (nextflow.file.http.XPath) and not a string. These special characters must be dealt with in some hidden way during caching which was causing the join operation to fail (i.e., the file object created from the original file and the one created from the cached file were not identical). So... after a few hours of banging my head against this, the problem was fixed by simply changing the type of meta.file defines in `assets/schema_input.json`: 

```
            "datafile": {
                "format": "string",
                "pattern": "^\\S+$",
                "errorMessage": "Data file for reads cannot contain spaces and must have extension 'cram', 'bam', '.fq.gz' or '.fastq.gz'",
                "meta": ["datafile"]
            },
```

Can you give it a try and see if the latest commits fix the problem?

**Comment by reichan1998** [comment]
Thank you for letting me know. It's great to hear that you have solved this problem @tkchafin ^^ I will try and get back to you later.

**Comment by reichan1998** [comment]
Hi @tkchafin, I have checked and your solution can fix the` -resume` issue. Happy weekend!

**Comment by tkchafin** [comment]
Thanks Weiwen! Can you click the "approve" button in the review so I can merge?

**Review by cduong11 — APPROVED** [review]

**Comment by reichan1998** [comment]
I have already approved. Thank you, Tyler!

**Comment by tkchafin** [comment]
Thanks for your review!

**Pull request merged**
