### PR TITLE
Patch 1.3.1

### PR DESCRIPTION
**Pull request by tkchafin**
- Fix for HiC CRAM inputs since 1.1.0
- For for PacBio FASTQ inputs since 1.3.0 
- Correct the license 

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/sanger-tol/readmapping/tree/master/.github/CONTRIBUTING.md)
- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [x] Usage Documentation in `docs/usage.md` is updated.
- [x] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by tkchafin** [comment]
Not sure what the EditorConfig fail is

**Comment by tkchafin** [comment]
editorconfig-checker is passing locally

**Review by cduong11 — APPROVED** [review]
Looks great, thank you! It's working well.

**Review by muffato — COMMENTED** [review]
- In this pipeline we also keep track of the citations in CITATIONS.md. Can you add bbtools there ?

**Pull request merged**
