### PR TITLE
Release 1.2

### PR DESCRIPTION
**Pull request by muffato**
It's release time !

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/sanger-tol/readmapping/tree/master/.github/CONTRIBUTING.md)
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by muffato** [comment]
@priyanka-surana : do you remember the version of the nf-core template you last used in this pipeline ?

**Comment by priyanka-surana** [comment]
> @priyanka-surana : do you remember the version of the nf-core template you last used in this pipeline ?

Based on the dates, my best guess is v2.9.

**Comment by muffato** [comment]
I'm getting a few `nf-core lint --release` failures:
```
╭─ [✗] 6 Pipeline Tests Failed ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                                                                                        │
│ nextflow_config: Config variable not found: params.validationShowHiddenParams                                                                                                          │
│ nextflow_config: Config variable not found: params.validationSchemaIgnoreParams                                                                                                        │
│ files_unchanged: .github/PULL_REQUEST_TEMPLATE.md does not match the template                                                                                                          │
│ files_unchanged: .github/workflows/branch.yml does not match the template                                                                                                              │
│ files_unchanged: .github/workflows/linting.yml does not match the template                                                                                                             │
│ schema_params: Param schema_ignore_params from nextflow config not found in nextflow_schema.json                                                                                       │
│                                                                                                                                                                                        │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

I'm looking into those.

**Comment by priyanka-surana** [comment]
> I'm getting a few `nf-core lint --release` failures:
> 
> ```
> ╭─ [✗] 6 Pipeline Tests Failed ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
> │                                                                                                                                                                                        │
> │ nextflow_config: Config variable not found: params.validationShowHiddenParams                                                                                                          │
> │ nextflow_config: Config variable not found: params.validationSchemaIgnoreParams                                                                                                        │
> │ files_unchanged: .github/PULL_REQUEST_TEMPLATE.md does not match the template                                                                                                          │
> │ files_unchanged: .github/workflows/branch.yml does not match the template                                                                                                              │
> │ files_unchanged: .github/workflows/linting.yml does not match the template                                                                                                             │
> │ schema_params: Param schema_ignore_params from nextflow config not found in nextflow_schema.json                                                                                       │
> │                                                                                                                                                                                        │
> ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
> ```

I think it is a nf-core version mismatch.

**Comment by muffato** [comment]
You were right ! No issue reported with nf-core 2.7

**Comment by muffato** [comment]
In that case, the PR is now ready for review

**Review by priyanka-surana — APPROVED** [review]
Since all the changes were reviewed in dev, I think we are good to merge.

**Pull request merged**
